FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir fastapi uvicorn pydantic

COPY module_b_appointments_medicines.py .

EXPOSE 5002

CMD ["uvicorn", "module_b_appointments_medicines:app", "--host", "0.0.0.0", "--port", "5002"]
